server.port: 8090

# JPA
spring.jpa.show-sql: true

# LOGGER
#logging.pattern.console:%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging:
  pattern:
    console: "%msg%n"
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    net.marco27.api.filesystemapi: DEBUG
app:
  numberoOfThreads: 10

