DROP TABLE FILE_STRUCTURE_CHILDREN;
DROP TABLE FILE_STRUCTURE;

CREATE TABLE FILE_STRUCTURE
(
	PATH	     VARCHAR2(255 CHAR) NOT NULL,
	EXT          VARCHAR2(255 CHAR),
	IS_DIRECTORY NUMBER(1,0)        NOT NULL,
	NAME         VARCHAR2(255 CHAR) NOT NULL,
	TIMESTAMP    VARCHAR2(255 CHAR) NOT NULL,
	PRIMARY KEY (PATH)
)
;
CREATE TABLE FILE_STRUCTURE_CHILDREN
( 
	FILE_STRUCTURE_PATH VARCHAR2(255 char) NOT NULL, 
	CHILDREN            VARCHAR2(255 CHAR) NOT NULL
)
;
ALTER TABLE FILE_STRUCTURE_CHILDREN
ADD CONSTRAINT FK_FILE_STRUCTURE_CHILDREN FOREIGN KEY
(
  FILE_STRUCTURE_PATH
)
REFERENCES FILE_STRUCTURE
(
  PATH
)
ENABLE
;
COMMIT;


INSERT INTO "APEX"."FILE_STRUCTURE" (PATH, IS_DIRECTORY, NAME, TIMESTAMP) VALUES ('1', '1', 'uno', TO_TIMESTAMP('2019-01-29 22:50:03.751000000', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into file_structure (ext, is_directory, name, timestamp, path) values (?, ?, ?, ?, ?)
insert into file_structure_children (file_structure_path, children) values (?, ?)